### ISSUE TITLE
Add spacing support to main layout components

### ISSUE THREAD

**Issue by julian-jelfs** [julianjelfs/ef-gud-elm#4]
The spacing module provides helper functions for most aspects of padding and margin. For each component that wants to provide padding and margin these features need to be wrapped with the relevant component's props wrapper. This is a bit of a pain. There could be a better way, but this is possibly just Elm's curse. It is not the best when it comes to abstraction. The end result will be nice for the user though.

**Comment by julianjelfs** [comment]
done
